# Generated by Django 4.2.5 on 2023-09-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_rename_contact_customer_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
    ]
