# Generated by Django 4.2.5 on 2023-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_service_provider_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2),
        ),
    ]
