# Generated by Django 4.2.5 on 2023-10-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_alter_service_provider_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=30)),
                ('benefits', models.CharField(max_length=40)),
                ('lapse_period', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('Service_Provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.service_provider')),
            ],
        ),
    ]
