# Generated by Django 4.2.5 on 2023-10-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='policy',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='insurance.policy'),
        ),
    ]
