# Generated by Django 4.2.5 on 2023-10-04 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='policy',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='insurance.policy'),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
    ]
