# Generated by Django 4.2.5 on 2023-10-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_payment_policy_alter_service_provider_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='insurance.customer'),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2),
        ),
    ]
