# Generated by Django 4.2.5 on 2023-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_payment_customer_alter_service_provider_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
    ]
